require("barbecue").setup({
	attach_navic = true, -- prevent barbecue from automatically attaching nvim-navic
	theme = "tokyonight",
	symbols = {
		modified = "●",
		ellipsis = "…",
		separator = "",
	},
	kinds = {
		File = " ",
		Module = " ",
		Namespace = " ",
		Package = " ",
		Class = " ",
		Method = " ",
		Property = " ",
		Field = " ",
		Constructor = " ",
		Enum = "練 ",
		Interface = "練 ",
		Function = " ",
		Variable = " ",
		Constant = " ",
		String = " ",
		Number = " ",
		Boolean = "◩ ",
		Array = " ",
		Object = " ",
		Key = " ",
		Null = "ﳠ ",
		EnumMember = " ",
		Struct = " ",
		Event = " ",
		Operator = " ",
		TypeParameter = " ",
	},
})
